#!/bin/bash
# Script to help add pgvector database to Railway
# This script provides instructions since Railway CLI requires interactive input

echo "🐘 Adding PostgreSQL with pgvector to Railway"
echo "=============================================="
echo ""
echo "Unfortunately, Railway CLI requires interactive input for adding databases."
echo "Here are your options:"
echo ""
echo "📋 OPTION 1: Use Railway CLI (Interactive)"
echo "-------------------------------------------"
echo "Run this command in your terminal:"
echo ""
echo "  railway add --database postgres"
echo ""
echo "When prompted:"
echo "  1. Select 'Database'"
echo "  2. Select 'PostgreSQL'"
echo ""
echo "⚠️  NOTE: This adds standard PostgreSQL without pgvector."
echo "   You'll need to check if pgvector can be enabled (unlikely)."
echo ""
echo ""
echo "📋 OPTION 2: Use Railway Dashboard (Recommended)"
echo "------------------------------------------------"
echo "This is the BEST way to get pgvector support:"
echo ""
echo "1. Open: https://railway.app"
echo "2. Navigate to project: recall-v2-demo"
echo "3. Click '+ New' → 'Database' or 'Template'"
echo "4. Search for 'pgvector' in the marketplace"
echo "5. Deploy 'PostgreSQL with pgvector' template"
echo ""
echo "This ensures pgvector is pre-installed and ready to use."
echo ""
echo ""
echo "📋 OPTION 3: Use Railway API (Advanced)"
echo "----------------------------------------"
echo "If you have a Railway API token, you could use the GraphQL API."
echo "However, this is more complex and not recommended."
echo ""
echo ""
echo "🎯 RECOMMENDED: Use Option 2 (Dashboard)"
echo "========================================="
echo ""
echo "After adding the pgvector database:"
echo ""
echo "1. The new database will have a DATABASE_URL variable"
echo "2. Railway will automatically connect your services to it"
echo "3. Redeploy your services (or push a new commit)"
echo "4. Migrations will automatically:"
echo "   - Enable pgvector extension"
echo "   - Convert embeddings to vector type"
echo "   - Create vector index"
echo ""
echo "5. Verify with:"
echo "   railway run node recall/scripts/enable-pgvector.js"
echo ""
echo "✅ Your app will automatically use fast pgvector queries!"
echo ""

